src/java/pl/gsm/bean/LoginBean.java
package pl.gsm.bean;

import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.servlet.http.HttpSession;
import pl.gsm.dao.DBManager;
import pl.gsm.dao.EmployeeUserBean;
import pl.gsm.entity.EmployeeUser;
import pl.gsm.entity.Shop;

@ManagedBean(name = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userPassword;
    private String userLogin;
    private Integer shopId;
    private static Shop shop;
    private static EmployeeUser user;

    private HttpSession getSession() {
        return (HttpSession) FacesContext.
                getCurrentInstance().
                getExternalContext().
                getSession(false);
    }

    public boolean hasRole() {
        return user.getUserTypeId().getType().equals("szef");
    }

    public String login() {
        if (EmployeeUserBean.checkLoginAndPassword(userLogin, userPassword)) {

            HttpSession httpSession = getSession();
            httpSession.setAttribute("username", userLogin);
            assignUser();
            assignShop();
            return "adddailysales";
        } else {
            FacesContext.getCurrentInstance().addMessage(null,
                    new FacesMessage(FacesMessage.SEVERITY_WARN,
                            "Błędne logowanie!",
                            "Spróbuj jeszcze raz!"));
            return "login";
        }
    }

    public String logout() {
        HttpSession httpSession = getSession();
        httpSession.invalidate();
        return "login";
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = EmployeeUser.md5(userPassword);
    }

    public String getUserLogin() {
        return userLogin;
    }

    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    public Integer getShopId() {
        return shopId;
    }

    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    public static Shop getShop() {
        return shop;
    }

    public static void setShop(Shop aSklep2) {
        shop = aSklep2;
    }

    public static EmployeeUser getUser() {
        return user;
    }

    public static void setUser(EmployeeUser aUser) {
        user = aUser;
    }

    public void assignShop() {
        EntityManager em = DBManager.getManager().createEntityManager();
        TypedQuery<Shop> query = em.createQuery("select e from Shop e where e.id = :id", Shop.class);
        query.setParameter("id", shopId);
        shop = query.getSingleResult();
        em.close();
    }

    public void assignUser() {
        EntityManager em = DBManager.getManager().createEntityManager();
        TypedQuery<EmployeeUser> query = em.createQuery("select e from EmployeeUser e where e.userLogin = :userLogin", EmployeeUser.class);
        query.setParameter("userLogin", userLogin);
        user = query.getSingleResult();
        em.close();
    }
}

src/java/pl/gsm/dao/ServiceBean.java
package pl.gsm.dao;

import java.awt.event.ActionEvent;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import pl.gsm.bean.LoginBean;
import pl.gsm.entity.DailySales;
import pl.gsm.entity.Service;

@ManagedBean(name = "serviceBean")
@SessionScoped
public class ServiceBean {

    private Service service = new Service();
    private EntityManager em;

    public String addService() {
        startEntityManager();
        service.setId(0);
        service.setShopId(LoginBean.getShop());
        em.merge(getService());
        stopEntityManager();
        return null;
    }

    public String deleteService() {
        startEntityManager();
        this.setService(em.find(Service.class, getService().getId()));
        em.remove(this.getService());
        stopEntityManager();
        return null;
    }

    public String loadService() {
        em = DBManager.getManager().createEntityManager();
        this.setService(em.find(Service.class, getService().getId()));
        em.close();
        return "/edit/editservice.xhtml";
    }

    public String editService() {
        startEntityManager();
        em.merge(getService());
        stopEntityManager();
        return "/addservice.xhtml";
    }

    private void startEntityManager() {
        em = DBManager.getManager().createEntityManager();
        em.getTransaction().begin();
    }

    private void stopEntityManager() {
        this.setService(new Service());
        em.getTransaction().commit();
        em.close();
    }

    public String sellService() {
        em = DBManager.getManager().createEntityManager();
        this.service = em.find(Service.class, service.getId());
        em.close();

        em = DBManager.getManager().createEntityManager();
        em.getTransaction().begin();

        DailySales tempDailySales = new DailySales();
        tempDailySales.setId(0);
        tempDailySales.setEmployeeUserId(LoginBean.getUser());
        tempDailySales.setShopId(LoginBean.getShop());
        tempDailySales.setCategory("SERWIS");
        tempDailySales.setProduct(service.getPhoneService());
        tempDailySales.setNumber(1);
        tempDailySales.setUnitPrice(service.getExpense());
        tempDailySales.setSumPrice(service.getExpense());
        em.merge(tempDailySales);
        service.setDateOfReceipt(new Date());
        em.merge(service);
        em.getTransaction().commit();
        em.close();

        return null;
    }

    public void serviceListener(ActionEvent ae) {
        String ids = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("serviceID");
        int id = Integer.parseInt(ids);
        this.getService().setId(id);
    }

    public List<Service> getServiceList() {
        em = DBManager.getManager().createEntityManager();
        TypedQuery<Service> query = em.createQuery("select e from Service e where e.shopId = :shopId and e.dateOfReceipt IS NULL", Service.class);
        query.setParameter("shopId", LoginBean.getShop());
        List serviceList = query.getResultList();
        em.close();
        return serviceList;
    }

    public List<Service> getSellServiceList() {
        em = DBManager.getManager().createEntityManager();
        TypedQuery<Service> query = em.createQuery("select e from Service e where e.shopId = :shopId and e.dateOfReceipt IS NOT NULL", Service.class);
        query.setParameter("shopId", LoginBean.getShop());
        List serviceList = query.getResultList();
        em.close();
        return serviceList;
    }

    public Service getService() {
        return service;
    }

    public void setService(Service service) {
        this.service = service;
    }

}

web/adddailysales.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:body onload="#{dailySalesBean.summaryListener(ae)}">
        <ui:composition template="/WEB-INF/templates/BasicTemplate.xhtml">
            <ui:define name="center_content">       
                #{dailySalesBean.summaryListener(ae)}
                #{dailySalesBean.setClosed()}
                <h:form>
                    <span class="title">
                        <h:panelGrid columns="2" style="width: 1180px">
                            <h:outputText value="ZESZYT"/>
                            <h:panelGrid columns="2" style="float: right">
                                <h:outputText value="#{loginBean.userLogin}"/>
                                <h:outputText value="#{dailySalesBean.today}" >
                                    <f:convertDateTime pattern="yyyy-MM-dd" />
                                </h:outputText>
                            </h:panelGrid>
                        </h:panelGrid>
                    </span>

                    <h:panelGrid columns="4" style="padding: 10px; width: 1200px">
                        <h:panelGrid columns="4">
                            <h:outputText value="Kategoria"/>
                            <h:selectOneMenu id="typeGoodsId" styleClass="som" 
                                             value="#{dailySalesBean.dailySales.category}" 
                                             binding="#{dailySalesBean.typeGoodsSOM}">
                                <f:selectItems value="#{dailySalesBean.categoryList}" 
                                               var="typeGoods" itemValue="#{typeGoods.categoryName}" 
                                               itemLabel="#{typeGoods.categoryName}"/>
                                <f:ajax render="productId"/>
                            </h:selectOneMenu> 

                            <h:panelGroup/><h:panelGroup/>
                            <h:outputText value="Produkt"/>
                            <h:selectOneMenu id="productId" styleClass="som" 
                                             value="#{dailySalesBean.goods.id}"
                                             binding="#{dailySalesBean.productSOM}">
                                <f:selectItem itemValue="#{dailySalesBean.goods.id}" itemLabel="Wybierz"/>
                                <f:selectItems value="#{dailySalesBean.goodsList}" 
                                               var="goods" itemValue="#{goods.id}" 
                                               itemLabel="#{goods.name}"/>
                                <f:ajax listener="#{dailySalesBean.dailySalesGoodsListener(ae)}" 
                                        render="unitPriceId sumPriceId num" /> 
                            </h:selectOneMenu> 
                            <h:outputText id="num" value="#{dailySalesBean.num}"/>
                            <h:outputText value="- na magazynie"/>
                        </h:panelGrid>

                        <h:panelGrid columns="2">
                            <h:outputText value="Inna kategoria"/>
                            <h:inputText id="otherCategoryId" styleClass="som" 
                                         value="#{dailySalesBean.dailySales.category}"
                                         disabled="true" binding="#{dailySalesBean.otherCategory}">
                                <f:validateLength maximum="30"/>
                            </h:inputText>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="otherCategoryId" style="color:red;margin:8px;" errorClass="error" />

                            <h:outputText value="Inny produkt"/>
                            <h:inputText id="otherProductId" styleClass="som" 
                                         value="#{dailySalesBean.dailySales.product}"
                                         disabled="true" binding="#{dailySalesBean.otherProduct}">
                                <f:validateLength maximum="30"/>
                            </h:inputText>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="otherProductId" style="color:red;margin:8px;" errorClass="error" />
                        </h:panelGrid>

                        <h:panelGrid columns="1">
                            <h:panelGrid columns="2">
                                <h:outputText value="Ilość"/>
                                <h:inputText id="numberId" styleClass="som" style="width: 20px;" 
                                             value="#{dailySalesBean.dailySales.number}"
                                             required="true">
                                    <f:validateLongRange minimum="1"/>
                                    <f:ajax listener="#{dailySalesBean.dailySalesNumberListener(ae)}" 
                                            render="sumPriceId"/>
                                </h:inputText>
                                <h:panelGroup></h:panelGroup>
                                <h:message for="numberId" style="color:red;margin:8px;" errorClass="error" />
                            </h:panelGrid>
                            <h:commandButton id="otherButton" styleClass="but" style="width: 100px;" 
                                             value="Inny produkt" disabled="#{dailySalesBean.close}"
                                             action="#{dailySalesBean.change()}" immediate="true">
                                <f:ajax render="typeGoodsId productId otherCategoryId otherProductId" /> 
                            </h:commandButton>
                        </h:panelGrid>

                        <h:panelGrid columns="2">
                            <h:outputText value="Cena"/>
                            <h:inputText id="unitPriceId" styleClass="som" 
                                         value="#{dailySalesBean.dailySales.unitPrice}">
                                <f:validateRequired/>
                                <f:ajax listener="#{dailySalesBean.dailySalesNumberListener(ae)}" render="sumPriceId"/>
                            </h:inputText>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="unitPriceId" style="color:red;margin:8px;" errorClass="error" />

                            <h:outputText value="Suma"/>
                            <h:outputText id="sumPriceId" styleClass="som" 
                                          value="#{dailySalesBean.dailySales.sumPrice}">
                            </h:outputText>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="sumPriceId" style="color:red;margin:8px;" errorClass="error" />
                        </h:panelGrid>

                    </h:panelGrid>
                    <h:commandButton id="addButtonId" styleClass="but" value="Dodaj" disabled="#{dailySalesBean.close}" 
                                     style="float: right; margin-right: 40px;" action="#{dailySalesBean.add()}">
                    </h:commandButton>

                    <h:panelGrid columns="2">
                        <p:calendar id="dateDownId" value="#{dailySalesBean.dateDown}" pattern="dd-MM-yyyy">
                            <p:ajax event="dateSelect" listener="#{dailySalesBean.summaryListener(ae)}" 
                                    update="dataTableId"/>
                        </p:calendar>
                        <p:calendar id="dateUpId" value="#{dailySalesBean.dateUp}" pattern="dd-MM-yyyy">
                            <p:ajax event="dateSelect" listener="#{dailySalesBean.summaryListener(ae)}" 
                                    update="dataTableId"/>
                        </p:calendar>
                    </h:panelGrid>



                    <h:dataTable id="dataTableId" class="goodsTable" 
                                 value="#{dailySalesBean.dailySalesList}" var="dailysales">
                        <h:column>
                            <h:column>
                                <h:selectBooleanCheckbox value="#{pdfBean.checked[dailysales.id]}" />
                            </h:column>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Id</f:facet>
                            <h:outputText value="#{dailysales.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Data</f:facet>
                            <h:outputText value="#{dailysales.sellingDate}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Sprzedawca</f:facet>
                            <h:outputText value="#{dailysales.employeeUserId.userLogin}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Sklep</f:facet>
                            <h:outputText value="#{dailysales.shopId.name}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Kategoria</f:facet>
                            <h:outputText value="#{dailysales.category}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Produkt</f:facet>
                            <h:outputText value="#{dailysales.product}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Ilość</f:facet>
                            <h:outputText value="#{dailysales.number}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Cena</f:facet>
                            <h:outputText value="#{dailysales.unitPrice}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Suma</f:facet>
                            <h:outputText value="#{dailysales.sumPrice}"/>
                        </h:column>
                        <h:column rendered="#{loginBean.hasRole()}">
                            <f:facet name="header">Usun</f:facet>
                            <h:commandLink value="Usun" immediate="true" disabled="#{not loginBean.hasRole()}"
                                           action="#{dailySalesBean.deleteDailySales()}"
                                           actionListener="#{dailySalesBean.dailySalesListener(ae)}">
                                <f:param name="dailysalesID" value="#{dailysales.id}"/>
                            </h:commandLink>
                        </h:column>
                    </h:dataTable>
                    <h:commandButton value="Faktura" styleClass="but" 
                                     style="width: 70px; margin: 10px; text-align: center" 
                                     action="#{pdfBean.loadCheckedDailySales()}"/>

                    <h:panelGrid columns="2">
                        <h:outputText value="Kasa dodatnia:"/>
                        <h:outputText id="cashPositiveId" value="#{dailySalesBean.cashPositive}"/>
                        <h:outputText value="Kasa ujemna:"/>
                        <h:outputText id="cashNegativeId" value="#{dailySalesBean.cashNegative}"/>
                        <h:outputText value="Suma z raportu:"/>
                        <h:inputText id="dailyReportId" value="#{dailySalesBean.dailyReport}">
                            <f:ajax listener="#{dailySalesBean.dailySalesReportListener(ae)}" 
                                    render="differenceReportId" />
                        </h:inputText>
                        <h:outputText value="Różnica:"/>
                        <h:outputText id="differenceReportId" value="#{dailySalesBean.differenceReport}"/>
                    </h:panelGrid>
                    <h:commandButton id="closeDay" styleClass="som" value="Zamknij dzień" 
                                     onclick="if (!confirm('Zamknąć dzień?'))
                                                 return false"
                                     immediate="true" action="#{dailySalesBean.closeAndSet()}">
                        <f:ajax render="dataTable2Id addButtonId therButtn 
                                typeGoodsId productId otherCategoryId otherProductId"/>
                    </h:commandButton>
                </h:form>
            </ui:define>
        </ui:composition>

    </h:body>

</html>

web/addservice.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition template="/WEB-INF/templates/BasicTemplate.xhtml">
            <ui:define name="center_content">       
                <h:form>
                    <span class="title">
                        <h:outputText value="DODAJ POZYCJĘ SERWISOWĄ"/>
                    </span>
                    <h:panelGrid columns="2" style="width: 1200px">
                        <h:panelGrid columns="2" style="margin: 0 auto">

                            <h:outputText value="Telefon"/>
                            <h:inputText id="phoneServiceId" 
                                         styleClass="som" style="margin: 5px;" 
                                         value="#{serviceBean.service.phoneService}">
                                <f:validateLength maximum="40"/>
                                <f:validateRequired/>
                            </h:inputText>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="phoneServiceId" style="color:red;margin:8px;" errorClass="error" />

                            <h:outputText value="IMEI"/>
                            <h:inputText id="imeiNumberId" 
                                         styleClass="som" style="margin: 5px;" 
                                         value="#{serviceBean.service.imeiNumber}">
                                <f:validateLength minimum="15" maximum="15"/>
                                <f:validateRequired/>
                            </h:inputText>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="imeiNumberId" style="color:red;margin:8px;" errorClass="error" />

                            <h:outputText value="Koszt"/>
                            <h:inputText id="expenseId" 
                                         styleClass="som" style="margin: 5px;" 
                                         value="#{serviceBean.service.expense}">
                                <f:validateDoubleRange minimum="0.0"/>
                                <f:validateRequired/>
                            </h:inputText>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="expenseId" style="color:red;margin:8px;" errorClass="error" />
                        </h:panelGrid>


                        <h:panelGrid columns="2" style="margin: 0 auto">
                            <h:outputText value="Opis usterki"/>
                            <h:inputTextarea id="productId" styleClass="som" 
                                             style="margin: 5px; resize: none; width: 200px; height: 60px" 
                                             value="#{serviceBean.service.description}">
                                <f:validateLength maximum="100"/>
                                <f:validateRequired/>
                            </h:inputTextarea>
                            <h:panelGroup></h:panelGroup>
                            <h:message for="productId" style="color:red;margin:8px;" errorClass="error" />
                        </h:panelGrid>
                    </h:panelGrid>

                    <h:commandButton id="addButton" styleClass="but" style="float: right; margin: 5px" 
                                     value="Dodaj" disabled="false"
                                     action="#{serviceBean.addService()}">
                    </h:commandButton>

                    <span class="title"><h:outputText value="SERWIS PRZYJĘTY"/></span>
                    <h:dataTable id="dataTableId" class="goodsTable" style="width: 1200px;" 
                                 value="#{serviceBean.serviceList}" var="service">
                        <h:column>
                            <f:facet name="header">Id</f:facet>
                            <h:outputText value="#{service.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Telefon</f:facet>
                            <h:outputText value="#{service.phoneService}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">IMEI</f:facet>
                            <h:outputText value="#{service.imeiNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Opis usterki</f:facet>
                            <h:outputText value="#{service.description}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Data przyjęcia</f:facet>
                            <h:outputText value="#{service.dateOfAdoption}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Data odbioru</f:facet>
                            <h:outputText value="#{service.dateOfReceipt}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Koszt</f:facet>
                            <h:outputText value="#{service.expense}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Wykonaj</f:facet>
                            <h:commandLink value="Wykonaj" immediate="true" onclick="if (!confirm('Wykonać serwis?'))
                                        return false"
                                           action="#{serviceBean.sellService()}"
                                           actionListener="#{serviceBean.serviceListener(ae)}">
                                <f:param name="serviceID" value="#{service.id}"/>
                            </h:commandLink>
                        </h:column>
                        <h:column rendered="#{loginBean.hasRole()}">
                            <f:facet name="header">Edytuj</f:facet>
                            <p:commandLink value="Edytuj" immediate="true" disabled="#{not loginBean.hasRole()}"
                                           action="#{serviceBean.loadService()}"
                                           actionListener="#{serviceBean.serviceListener(ae)}">
                                <f:param name="serviceID" value="#{service.id}"/>
                            </p:commandLink>
                        </h:column>
                        <h:column rendered="#{loginBean.hasRole()}">
                            <f:facet name="header">Usun</f:facet>
                            <h:commandLink value="Usun" immediate="true" disabled="#{not loginBean.hasRole()}"
                                           action="#{serviceBean.deleteService()}"
                                           actionListener="#{serviceBean.serviceListener(ae)}">
                                <f:param name="serviceID" value="#{service.id}"/>
                            </h:commandLink>
                        </h:column>
                    </h:dataTable>

                    <span class="title"><h:outputText value="SERWIS WYKONANY"/></span>
                    <h:dataTable id="dataSellTableId" class="goodsTable" style="width: 1200px;" 
                                 value="#{serviceBean.sellServiceList}" var="service">
                        <h:column>
                            <f:facet name="header">Id</f:facet>
                            <h:outputText value="#{service.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Telefon</f:facet>
                            <h:outputText value="#{service.phoneService}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">IMEI</f:facet>
                            <h:outputText value="#{service.imeiNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Opis usterki</f:facet>
                            <h:outputText value="#{service.description}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Data przyjęcia</f:facet>
                            <h:outputText value="#{service.dateOfAdoption}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Data odbioru</f:facet>
                            <h:outputText value="#{service.dateOfReceipt}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Koszt</f:facet>
                            <h:outputText value="#{service.expense}"/>
                        </h:column>
                        <h:column rendered="#{loginBean.hasRole()}">
                            <f:facet name="header">Usun</f:facet>
                            <h:commandLink value="Usun" immediate="true" disabled="#{not loginBean.hasRole()}"
                                           action="#{serviceBean.deleteService()}"
                                           actionListener="#{serviceBean.serviceListener(ae)}">
                                <f:param name="serviceID" value="#{service.id}"/>
                            </h:commandLink>
                        </h:column>
                    </h:dataTable>
                </h:form>  
            </ui:define>
        </ui:composition>

    </h:body>

</html>